apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myrole
  namespace: gamestore
  annotations:
          configmanagement.gke.io/namespace-slector: gamestore-selector 
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
