kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ashish
  annotations:
    configmanagement.gke.io/cluster-selector: selector1
subjects:
- kind: Group
  name: system:serviceaccounts:foo
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
